name: Dagger CI
on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Get Dagger version
        id: dagger_version
        uses: sagikazarmark/dagger-version-action@250543f4f12e1aa0161bd427eeb48ce3710fb408 # v0.0.2
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@d913e70051faf3b907d4dd96ef1161083c88c644 # v8.2.0
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          call: --is-ci=true run-ci
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
